/* CompiC.java */
/* Generated By:JavaCC: Do not edit this line. CompiC.java */
package edu.itsco;
import java.io.*;
import java.io.FileNotFoundException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.lang.String;


public class CompiC implements CompiCConstants {


private static ControlaVariables cVariables;

   private static PrintWriter archi;
  public static void main(String args[]) throws ParseException,SemanticException,FileNotFoundException {

    cVariables=new ControlaVariables();
    try{
    FileInputStream entrada=new FileInputStream("programa.mic");
    System.out.println("holaaaaa");

    CompiC compi=new CompiC(entrada);
    compi.principal();

    System.out.println("Compilo correctamente");
        }
    catch (FileNotFoundException fex)
    {
    System.err.println(fex.getMessage());
    }









  }

  static final public void principal() throws ParseException, ParseException, SemanticException, FileNotFoundException {archi = new PrintWriter("C://pruebasconjava//prueba.vb");
archi.println("Module modulo1");
archi.println("\u005ct sub main()");
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT:
      case FLOAT:
      case STRING:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      declararVariable();
      jj_consume_token(SEMIC);
    }
    label_2:
    while (true) {
      gramMetodos();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
    }
archi.println("\u005ct end sub");
archi.println("end module");
archi.close();
  }

  static final public void cuerpoMetodos() throws ParseException, SemanticException, FileNotFoundException, ParseException {
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRINTF:{
        imprimir();
        break;
        }
      case SCANF:{
        leer();
        break;
        }
      case IF:{
        gramaticaIf();
        break;
        }
      case SWITCH:{
        gramaticaSwitch();
        break;
        }
      case WHILE:{
        gramaticaWhile();
        break;
        }
      case DO:{
        gramaticaDowhile();
        break;
        }
      case ID:{
        asignacion();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PRINTF:
      case SCANF:
      case IF:
      case SWITCH:
      case WHILE:
      case DO:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
    }
  }

  static final private void declararVariable() throws ParseException, ParseException, SemanticException, FileNotFoundException {Token id;
Token tipo;
Variable v;
    tipo = tipoDato();
    id = jj_consume_token(ID);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGU:{
      cuerpoAsignacion();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      ;
    }
v=new Variable();
        v.setNombre(id.image);
        v.setTipo(tipo.image);
        v.setLocal(false);
        cVariables.agregarVariable(v);
        System.out.println(id.image + " de tipo " +tipo.image);
        cVariables.existeVariable(v);
//esto es lo que se va a escribir en el archivo de salida
if(tipo.image=="int"||tipo.image=="INT"){
archi.println("\u005ct\u005ct\u005ct Dim "+id.image+" as Integer");
}else if(tipo.image=="string"||tipo.image=="STRING"){
archi.println("\u005ct\u005ct\u005ct Dim "+id.image+" as String");
}else{
archi.println("\u005ct\u005ct\u005ct Dim "+id.image+" as Double");
}
  }

  static final private Token tipoDato() throws ParseException, SemanticException, FileNotFoundException {Token tipo;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      tipo = jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      tipo = jj_consume_token(FLOAT);
      break;
      }
    case STRING:{
      tipo = jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return tipo;}
    throw new Error("Missing return statement in function");
  }

  static final private void gramMetodos() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(FUNCTION);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VOID:{
      jj_consume_token(VOID);
      break;
      }
    case INT:
    case FLOAT:
    case STRING:{
      tipoDato();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(ID);
    jj_consume_token(OPP);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:
    case FLOAT:
    case STRING:{
      parametros();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
    jj_consume_token(CLP);
    jj_consume_token(OPK);
    cuerpoMetodos();
    jj_consume_token(CLK);
  }

  static final private void parametros() throws ParseException, SemanticException, FileNotFoundException {
    declararVariable();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 49:{
        ;
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        break label_4;
      }
      jj_consume_token(49);
      declararVariable();
    }
  }

  static final private void imprimir() throws ParseException, SemanticException, FileNotFoundException {Token id;
    jj_consume_token(PRINTF);
    jj_consume_token(OPP);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_ENTERO:
    case VALOR_FLOAT:
    case VALOR_STRING:{
      valores();
      break;
      }
    case ID:{
      id = jj_consume_token(ID);
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 49:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      jj_consume_token(49);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VALOR_ENTERO:
      case VALOR_FLOAT:
      case VALOR_STRING:{
        valores();
        break;
        }
      case ID:{
        jj_consume_token(ID);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(CLP);
    jj_consume_token(SEMIC);

  }

  static final private void valores() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_ENTERO:{
      jj_consume_token(VALOR_ENTERO);
      break;
      }
    case VALOR_STRING:{
      jj_consume_token(VALOR_STRING);
      break;
      }
    case VALOR_FLOAT:{
      jj_consume_token(VALOR_FLOAT);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final private void leer() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(SCANF);
    jj_consume_token(OPP);
    jj_consume_token(ID);
    jj_consume_token(CLP);
    jj_consume_token(SEMIC);
  }

  static final private void gramaticaIf() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(IF);
    jj_consume_token(OPP);
    condicion();
    jj_consume_token(CLP);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OPK:{
      jj_consume_token(OPK);
      cuerpoMetodos();
      jj_consume_token(CLK);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
  }

  static final private void gramaticaSwitch() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(SWITCH);
    jj_consume_token(OPP);
    jj_consume_token(ID);
    jj_consume_token(CLP);
    jj_consume_token(OPK);
    label_6:
    while (true) {
      jj_consume_token(CASE);
      jj_consume_token(VALOR_ENTERO);
      jj_consume_token(50);
      cuerpoMetodos();
      jj_consume_token(BREAK);
      jj_consume_token(SEMIC);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEF:{
      jj_consume_token(DEF);
      jj_consume_token(50);
      cuerpoMetodos();
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    jj_consume_token(CLK);
  }

  static final private void gramaticaWhile() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(WHILE);
    jj_consume_token(OPP);
    condicion();
    jj_consume_token(CLP);
    jj_consume_token(OPK);
    cuerpoMetodos();
    jj_consume_token(CLK);
  }

  static final private void gramaticaDowhile() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(DO);
    jj_consume_token(OPK);
    cuerpoMetodos();
    jj_consume_token(CLK);
    jj_consume_token(WHILE);
    jj_consume_token(OPP);
    condicion();
    jj_consume_token(CLP);
    jj_consume_token(SEMIC);
  }

  static final private void condicion() throws ParseException, SemanticException, FileNotFoundException {
    condicionSimple();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        break label_7;
      }
      opLogico();
      condicionSimple();
    }
  }

  static final private void condicionSimple() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NOT:{
      jj_consume_token(NOT);
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      jj_consume_token(ID);
      break;
      }
    case VALOR_ENTERO:
    case VALOR_FLOAT:
    case VALOR_STRING:{
      valores();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    opRelacional();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      jj_consume_token(ID);
      break;
      }
    case VALOR_ENTERO:
    case VALOR_FLOAT:
    case VALOR_STRING:{
      valores();
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final private void opRelacional() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAY:{
      jj_consume_token(MAY);
      break;
      }
    case MEN:{
      jj_consume_token(MEN);
      break;
      }
    case MAYIG:{
      jj_consume_token(MAYIG);
      break;
      }
    case MENIG:{
      jj_consume_token(MENIG);
      break;
      }
    case DIF:{
      jj_consume_token(DIF);
      break;
      }
    case EQUAL:{
      jj_consume_token(EQUAL);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final private void opLogico() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AND:{
      jj_consume_token(AND);
      break;
      }
    case OR:{
      jj_consume_token(OR);
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final private void asignacion() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(ID);
    cuerpoAsignacion();
    jj_consume_token(SEMIC);
  }

  static final private void cuerpoAsignacion() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(IGU);
    opBasica();
  }

  static final private void opBasica() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VALOR_ENTERO:
    case VALOR_FLOAT:
    case VALOR_STRING:{
      valores();
      break;
      }
    case ID:{
      jj_consume_token(ID);
      break;
      }
    case OPP:{
      opParentesis();
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUM:
      case RES:
      case MUL:
      case DIV:
      case MOD:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_8;
      }
      opAritmetico();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VALOR_ENTERO:
      case VALOR_FLOAT:
      case VALOR_STRING:{
        valores();
        break;
        }
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case OPP:{
        opParentesis();
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final private void opParentesis() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(OPP);
    opBasica();
    jj_consume_token(CLP);
  }

  static final private void opAritmetico() throws ParseException, SemanticException, FileNotFoundException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SUM:{
      jj_consume_token(SUM);
      break;
      }
    case RES:{
      jj_consume_token(RES);
      break;
      }
    case MUL:{
      jj_consume_token(MUL);
      break;
      }
    case DIV:{
      jj_consume_token(DIV);
      break;
      }
    case MOD:{
      jj_consume_token(MOD);
      break;
      }
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final private void gramaticaFor() throws ParseException, SemanticException, FileNotFoundException {
    jj_consume_token(FOR);
    jj_consume_token(OPP);
    jj_consume_token(ID);
    cuerpoAsignacion();
    jj_consume_token(SEMIC);
    condicion();
    jj_consume_token(SEMIC);
    jj_consume_token(ID);
    cuerpoAsignacion();
    jj_consume_token(CLP);
    jj_consume_token(OPK);
    cuerpoMetodos();
    jj_consume_token(CLK);
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public CompiCTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[26];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xe0,0x100000,0xc2e00,0xc2e00,0x0,0xe0,0x1e0,0xe0,0x0,0x0,0x0,0x0,0x0,0x400000,0x4000,0x8000,0x0,0x0,0x0,0x0,0x0,0x0,0x1000000,0xf0000000,0x1000000,0xf0000000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x10000,0x10000,0x2,0x0,0x0,0x0,0x20000,0x1e000,0x20000,0x1e000,0xe000,0x0,0x0,0x0,0x300,0x400,0x1e000,0x1e000,0xfc,0x300,0x1e000,0x1,0x1e000,0x1,};
   }

  /** Constructor with InputStream. */
  public CompiC(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public CompiC(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public CompiC(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiCTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public CompiC(CompiCTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiCTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 26; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[51];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 26; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 51; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
