/* Generated By:JavaCC: Do not edit this line. CompiCConstants.java */
package edu.itsco;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 5;
  /** RegularExpression Id. */
  int FLOAT = 6;
  /** RegularExpression Id. */
  int STRING = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int PRINTF = 9;
  /** RegularExpression Id. */
  int SCANF = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int ELSE = 12;
  /** RegularExpression Id. */
  int SWITCH = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int DEF = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int FUNCTION = 20;
  /** RegularExpression Id. */
  int SEMIC = 21;
  /** RegularExpression Id. */
  int OPK = 22;
  /** RegularExpression Id. */
  int CLK = 23;
  /** RegularExpression Id. */
  int OPP = 24;
  /** RegularExpression Id. */
  int CLP = 25;
  /** RegularExpression Id. */
  int OPC = 26;
  /** RegularExpression Id. */
  int CLC = 27;
  /** RegularExpression Id. */
  int SUM = 28;
  /** RegularExpression Id. */
  int RES = 29;
  /** RegularExpression Id. */
  int MUL = 30;
  /** RegularExpression Id. */
  int DIV = 31;
  /** RegularExpression Id. */
  int MOD = 32;
  /** RegularExpression Id. */
  int IGU = 33;
  /** RegularExpression Id. */
  int EQUAL = 34;
  /** RegularExpression Id. */
  int MAY = 35;
  /** RegularExpression Id. */
  int MEN = 36;
  /** RegularExpression Id. */
  int MAYIG = 37;
  /** RegularExpression Id. */
  int MENIG = 38;
  /** RegularExpression Id. */
  int DIF = 39;
  /** RegularExpression Id. */
  int AND = 40;
  /** RegularExpression Id. */
  int OR = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int letra = 43;
  /** RegularExpression Id. */
  int digito = 44;
  /** RegularExpression Id. */
  int VALOR_ENTERO = 45;
  /** RegularExpression Id. */
  int VALOR_FLOAT = 46;
  /** RegularExpression Id. */
  int VALOR_STRING = 47;
  /** RegularExpression Id. */
  int ID = 48;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"int\"",
    "\"float\"",
    "\"string\"",
    "\"void\"",
    "\"printf\"",
    "\"scanf\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"for\"",
    "\"while\"",
    "\"do\"",
    "\"function\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "<letra>",
    "<digito>",
    "<VALOR_ENTERO>",
    "<VALOR_FLOAT>",
    "<VALOR_STRING>",
    "<ID>",
    "\",\"",
    "\":\"",
  };

}
